### ISSUE TITLE
No textile builds for Lift3 in Maven central

### ISSUE THREAD

**Issue by pdyraga** [liftmodules/textile#13]
Although the README says Lift3 builds are available I can't find them in Maven central:
https://search.maven.org/#search%7Cga%7C1%7Cnet.liftmodules.textile

We are currently migrating our Lift2.6 application into Lift3 and this is a blocker for us.

Can you please build and publish those versions into the central repository?

**Comment by pdyraga** [comment]
Sorry, I just realized those are just snapshot builds.

**Comment by Shadowfiend** [comment]
@karma4u101 @d6y do we want to look at publishing non-snapshot versions for 3.x? Not sure if there's something specific we're trying to hold out for.

**Comment by karma4u101** [comment]
They are,  @pdyraga if you are using sbt add the following resolvers 

resolvers ++= Seq("snapshots"     at "https://oss.sonatype.org/content/repositories/snapshots",
                  "staging"       at "https://oss.sonatype.org/content/repositories/staging",
                  "releases"      at "https://oss.sonatype.org/content/repositories/releases"
)

and this in libraryDependencies
"net.liftmodules" %% "textile_3.1" % "1.4-SNAPSHOT",

**Comment by karma4u101** [comment]
@Shadowfiend I needed the textile module in the demo project so I published snapshots for it (and the widgets module), I have not been testing it that hard so I don't really know the status of the upgrade.

**Comment by Shadowfiend** [comment]
Gotcha! Thanks for the clarification :)

**Comment by d6y** [comment]
Publishing non-snapshots for 3.0 and 3.1 shouldn't be a problem. I'll see if I can give it a while in the next few days...

**Comment by pdyraga** [comment]
As a workaround, before non-snapshots are ready, I published a snapshot version for Lift 3.0.1 and Scala 2.11 today. This way the only one missing. Now we should have all versions mentioned in README covered:

![image](https://user-images.githubusercontent.com/4712360/34669640-f029d0e2-f472-11e7-9fc1-175bfe20c1d7.png)

**Comment by pdyraga** [comment]
I published a snapshot build for `3.0_2.12` today, we are still testing if everything works as expected.
